### ISSUE TITLE
Input en taal

### ISSUE THREAD

**Issue by issamvandecoderclass** [ayachi-code/space-finder#1]
Ik heb gekeken naar je code, maar je input bar is Engels, maar de informatie tab Nederlands. Daar zal ik even op kijken Bilal. Veel succes

**Comment by ayachi-code** [comment]
Dankjewel voor je feedback, Ik heb een grotendeels gefixed. Het is alleen nog het begin die informatie is een placeholder ik verwijder de placeholder als, alle informatie er is
